### ISSUE TITLE
Installation failed with default values

### ISSUE THREAD

**Issue by ufukdev** [jr200/nats-iam-broker#18]
I'm trying to install this helm chart with default values.

```yaml
  # configuration of the third-party identity provider that supplied the JWT token
  idp:
    - description: elysia-admin
      # The client ID for the identity provider
      client_id: elysia-admin

      # URLs of the identity provider issuer
      issuer_url: https://blabla/realms/blabla

      validation:
        # claims required to be present on the incoming JWT validation
        claims:
          - aud
          - iat
          - exp
          - sub
        # Expected values for the audience claim of the JWT
        # to skip this check set it to []
        aud:
          - elysia-admin
        # acceptable expiration bounds for incoming JWT
        exp:
          min: 1m0s
          max: 2h

```

Im only changing this fields. But getting error in pod

```

3:08PM DBG merging config /config/app.yaml
2025-06-04T15:08:08.809769903Z 3:08PM DBG merging config /config/idp.yaml
2025-06-04T15:08:08.809839994Z 3:08PM DBG merging config /config/rbac-accounts.yaml
2025-06-04T15:08:08.809854942Z 3:08PM DBG merging config /config/rbac-roles.yaml
2025-06-04T15:08:08.809915876Z 3:08PM DBG merging config /config/rbac-bindings.yaml
2025-06-04T15:08:08.811754031Z 3:08PM DBG skipped parsing nkey: <<< readFile "/vault/secrets/service/xkey.nk" >>> (illegal base32 data at input byte 0)
2025-06-04T15:08:08.812481210Z 3:08PM DBG skipped parsing nkey: <<< readFile "/vault/secrets/iam-broker/a-signer.nk" >>> (illegal base32 data at input byte 0)
2025-06-04T15:08:08.812515595Z 3:08PM DBG template-pattern: <<<[^\n]*?>>>
3:08PM TRC filter:readFile /vault/secrets/service/xkey.nk
2025-06-04T15:08:08.812521967Z 3:08PM TRC [render failed]. input=<<< readFile "/vault/secrets/service/xkey.nk" >>>, context=map[], err=template: config:1:4: executing "config" at <readFile "/vault/secrets/service/xkey.nk">: error calling readFile: open /vault/secrets/service/xkey.nk: no such file or directory
[service stderr]: error populating config: yaml: unmarshal errors:
2025-06-04T15:08:08.813584562Z   line 17: field token_bounds not found in type server.NATS
2025-06-04T15:08:08.813610390Z 3:08PM TRC filter:readFile /vault/secrets/iam-broker/a-signer.nk
2025-06-04T15:08:08.813620199Z 3:08PM TRC [render failed]. input=<<< readFile "/vault/secrets/iam-broker/a-signer.nk" >>>, context=map[], err=template: config:1:4: executing "config" at <readFile "/vault/secrets/iam-broker/a-signer.nk">: error calling readFile: open /vault/secrets/iam-broker/a-signer.nk: no such file or directory
2025-06-04T15:08:08.813625229Z 3:08PM DBG skipped parsing nkey: <<< readFile "/vault/secrets/service/xkey.nk" >>> (illegal base32 data at input byte 0)
2025-06-04T15:08:08.813628645Z 3:08PM DBG skipped parsing nkey: <<< readFile "/vault/secrets/iam-broker/a-signer.nk" >>> (illegal base32 data at input byte 0)
2025-06-04T15:08:08.813632792Z 3:08PM ERR bad configuration error="error populating config: yaml: unmarshal errors:\n  line 17: field token_bounds not found in type server.NATS"```
